FROM node:24-alpine

# Habilitar pnpm
RUN corepack enable pnpm

WORKDIR /app

# Copiar archivos de dependencias
COPY package.json pnpm-lock.yaml ./
COPY .npmrc* ./

# Instalar dependencias
RUN pnpm install --frozen-lockfile

# Copiar configuración
COPY nest-cli.json tsconfig*.json ./

EXPOSE $PORT

CMD ["pnpm", "run", "start:dev"]
