export const NATS_SERVICE = 'NATS_SERVICE';
export const USERS_SERVICE = 'USERS_SERVICE';
export const INTEGRATION_SERVICE = 'INTEGRATION_SERVICE';
export const AUTH_SERVICE = 'AUTH_SERVICE';
export const PAYMENT_SERVICE = 'PAYMENT_SERVICE';
export const MEMBERSHIP_SERVICE = 'MEMBERSHIP_SERVICE';
export const POINT_SERVICE = 'POINT_SERVICE';
